In [1]:
import numpy as np

In [2]:
a= np.array([0,1,2])
a

array([0, 1, 2])

In [3]:
e= np.array([1,3,5,], dtype='int64')

In [4]:
e.dtype

dtype('int64')

In [5]:
type(e)

numpy.ndarray

In [6]:
a.ndim

1

In [8]:
c= np.array([[1,2],[5,6]])
c

array([[1, 2],
       [5, 6]])

In [10]:
c.ndim

2

In [11]:
c.shape

(2, 2)

In [12]:
a.shape

(3,)

In [13]:
len(c.shape)==c.ndim

True

In [29]:
aa= np.array([1,2,3,4])
aa

array([1, 2, 3, 4])

In [15]:
bb= np.array([[1,2,3],[4,5,6]])
bb

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
d=np.array([[1,2],[1,2,3]])
d

array([list([1, 2]), list([1, 2, 3])], dtype=object)

In [18]:
d.shape

(2,)

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.empty((2,4), dtype=np.float32)

array([[0.0000000e+00, 0.0000000e+00, 1.6833755e+12, 0.0000000e+00],
       [2.8025969e-45, 0.0000000e+00,           nan,           nan]],
      dtype=float32)

In [22]:
np.ones((2,2), dtype=np.int32)

array([[1, 1],
       [1, 1]])

In [30]:
aa

array([1, 2, 3, 4])

In [32]:
np.ones_like(aa)

array([1, 1, 1, 1])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [40]:
np.arange(0.7, 1.88, 0.15)

array([0.7 , 0.85, 1.  , 1.15, 1.3 , 1.45, 1.6 , 1.75])

In [41]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [42]:
np.linspace(1.4,20,5)

array([ 1.4 ,  6.05, 10.7 , 15.35, 20.  ])

In [44]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [47]:
1/a

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [49]:
a= np.array([[4,8,12],[16,20,24]])

In [50]:
a

array([[ 4,  8, 12],
       [16, 20, 24]])

In [51]:
b= np.identity(3)

In [52]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a.dot(b)

array([[ 4.,  8., 12.],
       [16., 20., 24.]])

In [54]:
np.dot(a,b)

array([[ 4.,  8., 12.],
       [16., 20., 24.]])

In [2]:
a= np.array([[1,2,3],[4,5,6]])

In [3]:
b=a
a=a*2

In [4]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b=a
a*=2

In [7]:
b

array([[ 4,  8, 12],
       [16, 20, 24]])

In [8]:
a

array([[ 4,  8, 12],
       [16, 20, 24]])

In [9]:
A= np.array([[1,4,2,3,4,5],[2,5,6,5,2,1]])
B=np.array([1,2,3,4,5,6])
C= np.array([3.5,2.4])
D=np.array([[2.2,2.2,2.2,2.2,2.2,2.2],[2.2,2.2,2.2,2.2,2.2,2.2]])

In [12]:
R =3*A-D
R

array([[ 0.8,  9.8,  3.8,  6.8,  9.8, 12.8],
       [ 3.8, 12.8, 15.8, 12.8,  3.8,  0.8]])

In [26]:
X=C.dot(R).dot(B)

In [28]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
a[1]

1

In [30]:
a[-1]

4

In [31]:
a[2:4]

array([2, 3])

In [32]:
a[:5:2]

array([0, 2, 4])

In [33]:
a[::]

array([0, 1, 2, 3, 4])

In [34]:
a[::-1]

array([4, 3, 2, 1, 0])

In [35]:
b= np.array([[1,3,5,7],[2,4,6,8],[3,6,9,12]])
b

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [36]:
b[1,3]

8

In [37]:
b[0]

array([1, 3, 5, 7])

In [38]:
b[0,:]

array([1, 3, 5, 7])

In [39]:
b[:,2]

array([5, 6, 9])

In [46]:
b[1,1:3]

array([4, 6])

In [47]:
b[1:,::2]

array([[2, 6],
       [3, 9]])

In [48]:
b[:,::-1]

array([[ 7,  5,  3,  1],
       [ 8,  6,  4,  2],
       [12,  9,  6,  3]])

In [49]:
b[::2]

array([[ 1,  3,  5,  7],
       [ 3,  6,  9, 12]])

In [50]:
C= np.array([[1,0,3],[0,5,0]])
C

array([[1, 0, 3],
       [0, 5, 0]])

In [51]:
np.logical_or(C==0, C>3)

array([[False,  True, False],
       [ True,  True,  True]])

In [52]:
np.logical_not(C==0)

array([[ True, False,  True],
       [False,  True, False]])

In [54]:
(C==0).any()

True

In [55]:
(C==0).all()

False

In [56]:
(C>=0).all()

True

In [63]:
A=([[2,4],[0,1]])
B=([[1,1],[1,1]])
C= np.ones([2,2], dtype='int64')
C

array([[1, 1],
       [1, 1]], dtype=int64)

In [71]:
C = np.divide(B,A)
C

C:\Users\Hanul Lee\AppData\Local\conda\conda\envs\da36\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([[0.5 , 0.25],
       [ inf, 1.  ]])

In [78]:
C[np.isinf(C)] = -1
C

array([[ 0.5 ,  0.25],
       [-1.  ,  1.  ]])

In [79]:
a

array([0, 1, 2, 3, 4])

In [81]:
i= np.array([2,1,0,3])
a[i]

array([2, 1, 0, 3])

In [84]:
b= np.array([[1,3,5,7],[2,4,6,8],[3,6,9,12]])
b

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [83]:
b.reshape(4,3)

array([[ 1,  3,  5],
       [ 7,  2,  4],
       [ 6,  8,  3],
       [ 6,  9, 12]])

In [86]:
b.reshape((6,-1))

array([[ 1,  3],
       [ 5,  7],
       [ 2,  4],
       [ 6,  8],
       [ 3,  6],
       [ 9, 12]])

In [87]:
b.T

array([[ 1,  2,  3],
       [ 3,  4,  6],
       [ 5,  6,  9],
       [ 7,  8, 12]])

In [88]:
a = np.array([1,2])
b=np.array([3,4])

In [90]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [91]:
a2= a.reshape((1,2))
b2= b.reshape((1,2))

In [92]:
a2

array([[1, 2]])

In [93]:
b2

array([[3, 4]])

In [95]:
np.concatenate((a2,b2), axis=1)

array([[1, 2, 3, 4]])

In [96]:
np.concatenate((a2,b2), axis=0)

array([[1, 2],
       [3, 4]])

In [97]:
d= np.arange(12).reshape(3,4)
e= np.arange(16).reshape(4,4)

In [99]:
np.concatenate((d,e), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.array([[1,1],[1,1],[1,1]]) + np.array([1])

array([[2, 2],
       [2, 2],
       [2, 2]])

In [107]:
np.array([1]).shape

(1,)

In [110]:
np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])+ np.array([1,2,3,4,5])

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [111]:
np.array([[1,1,1],[1,1,1]) + np.array([1,2])

SyntaxError: invalid syntax (<ipython-input-111-7909c50e92e7>, line 1)