In [30]:
import pandas as pd
import numpy as np

In [2]:
data= pd.Series([0.25, 0.5, 0.75, 1.0])

In [7]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [8]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
population_dict = {'Califonia': 2644542,
                  'Texas': 3824332,
                  'New York': 1954332,
                  'Florida': 1234523,
                  'Illinois':1265432}

In [5]:
population= pd.Series(population_dict)

In [6]:
population

Califonia    2644542
Florida      1234523
Illinois     1265432
New York     1954332
Texas        3824332
dtype: int64

In [10]:
data = pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])

In [11]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [14]:
data[['b','c']]

b    0.50
c    0.75
dtype: float64

In [16]:
data['b':'d']

b    0.50
c    0.75
d    1.00
dtype: float64

In [17]:
pd.Series(6, index=[100,200,300,400])  #브로드캐스팅

100    6
200    6
300    6
400    6
dtype: int64

In [18]:
pd.Series({2:'a',1:'b',3:'c'}, index=[3,2])

3    c
2    a
dtype: object

In [46]:
area_dict = {'Califonia': 24542,
                  'Texas': 24332,
                  'New York': 54332,
                  'Florida': 34523,
                  'Illinois':65432}

In [47]:
area= pd.Series(area_dict)

In [48]:
area

Califonia    24542
Florida      34523
Illinois     65432
New York     54332
Texas        24332
dtype: int64

In [49]:
states= pd.DataFrame({'population':population,'area':area})

In [50]:
states

area  population
Califonia  24542     2644542
Florida    34523     1234523
Illinois   65432     1265432
New York   54332     1954332
Texas      24332     3824332

In [51]:
pd.DataFrame(population, columns=['population'])

population
Califonia     2644542
Florida       1234523
Illinois      1265432
New York      1954332
Texas         3824332

In [52]:
pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.079135  0.676928
b  0.103498  0.916317
c  0.694237  0.284683

In [53]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [54]:
states['area']

Califonia    24542
Florida      34523
Illinois     65432
New York     54332
Texas        24332
Name: area, dtype: int64

In [55]:
states.population

Califonia    2644542
Florida      1234523
Illinois     1265432
New York     1954332
Texas        3824332
Name: population, dtype: int64

In [56]:
states['density']= states['population']/states['area']

In [57]:
states

area  population     density
Califonia  24542     2644542  107.755766
Florida    34523     1234523   35.759436
Illinois   65432     1265432   19.339650
New York   54332     1954332   35.970183
Texas      24332     3824332  157.172941

In [58]:
states.iloc[:1,:]

area  population     density
Califonia  24542     2644542  107.755766

In [59]:
states.loc[:'New York',:"population"]

area  population
Califonia  24542     2644542
Florida    34523     1234523
Illinois   65432     1265432
New York   54332     1954332

In [44]:
states.loc[states.density >100] =10

In [45]:
states

area  population    density
Califonia      0           0   0.000000
Florida    34523     1234523  35.759436
Illinois   65432     1265432  19.339650
New York   54332     1954332  35.970183
Texas          0           0   0.000000

In [60]:
test = states

In [62]:
test.loc[test.density>100, ['density']] =10

In [63]:
test

area  population    density
Califonia  24542     2644542  10.000000
Florida    34523     1234523  35.759436
Illinois   65432     1265432  19.339650
New York   54332     1954332  35.970183
Texas      24332     3824332  10.000000

In [64]:
states

area  population    density
Califonia  24542     2644542  10.000000
Florida    34523     1234523  35.759436
Illinois   65432     1265432  19.339650
New York   54332     1954332  35.970183
Texas      24332     3824332  10.000000

In [70]:
A= pd.DataFrame([[17,3],[17,11]], columns=['A','B'])

In [72]:
A-2

A  B
0  15  1
1  15  9

In [73]:
A- np.array([2,3])

A  B
0  15  0
1  15  8

In [77]:
A - A.iloc[0]

A  B
0  0  0
1  0  8

In [78]:
B= pd.DataFrame([[0,1,2],[5,8,7],[3,0,3]], columns=['B','A','C'])

In [79]:
B

B  A  C
0  0  1  2
1  5  8  7
2  3  0  3

In [80]:
A+B

A     B   C
0  18.0   3.0 NaN
1  25.0  16.0 NaN
2   NaN   NaN NaN

In [83]:
result=A/B

In [92]:
result.isnull()

A      B     C
0  False  False  True
1  False  False  True
2   True   True  True

In [94]:
a = np.array([1,2])
b= np.array([3,4])

In [101]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [102]:
a2 = a.reshape((1,2))
b2= b.reshape((1,2))

In [103]:
a2

array([[1, 2]])

In [104]:
b2

array([[3, 4]])

In [109]:
np.concatenate((a2,b2), axis=1)

array([[1, 2, 3, 4]])

In [115]:
df1 = pd.DataFrame([['A1','B1'],['A2','B2']], index=[1,2], columns=['A','B'])

In [116]:
df2 = pd.DataFrame([['A3','B3'],['A4','B4']], index=[3,4], columns=['A','B'])

In [117]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [118]:
df3 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=['A','B'])
df4 = pd.DataFrame([['C0','D0'],['C1','D1']], columns=['C','D'])

In [119]:
pd.concat([df3,df4], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [120]:
df5 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=['A','B'])
df6 = pd.DataFrame([['A2','B2'],['A3','B3']], columns=['A','B'])

In [124]:
pd.concat([df5,df6], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [125]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [127]:
df1= pd.DataFrame([['Bob','Accounting'],['Jake','Engineering'],['Lisa','Engineering'],['Sue','HR']], columns=['employee','Group'])
df2= pd.DataFrame([['Bob',2008],['Jake',2012],['Lisa',2004],['Sue',2014]], columns=['employee','hire_date'])

In [128]:
pd.merge(df1,df2)  # one to one join(같은 컬럼 기준으로 Join)

employee        Group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [130]:
df3= pd.merge(df1,df2)
df4 = pd.DataFrame([['Accounting','Carly'],['Engineering','Guido'],['HR','Steve']],columns=['Group','Supervisor'])

In [131]:
pd.merge(df3,df4)  # Many to one join

employee        Group  hire_date Supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [132]:
df5 = pd.DataFrame([['Accounting','math'],['Accounting','spreadsheets'],['Engineering','Coding'],['Engineering','Linux'],['HR','Spreadsheets'],['HR','organization']], columns=['Group','Skills'])

In [133]:
pd.merge(df1,df5)  #many to many 

employee        Group        Skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        Coding
3     Jake  Engineering         Linux
4     Lisa  Engineering        Coding
5     Lisa  Engineering         Linux
6      Sue           HR  Spreadsheets
7      Sue           HR  organization

In [134]:
df1

employee        Group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [135]:
df6= pd.DataFrame([['Bob',70000],['Jake',80000],['Lisa',120000],['Sue',90000]], columns=['name','Salary'])

In [137]:
tmp= pd.merge(df1,df6, left_on='employee', right_on='name')
tmp

employee        Group  name  Salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [139]:
tmp.drop('name',axis=1)  # 따로 저장해서 써야됨. 원본안바뀜

employee        Group  Salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [140]:
pd.merge(df1,df2)

employee        Group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [153]:
pd.merge(df1,df2, left_index=True, right_index=True)

employee_x        Group employee_y  hire_date
0        Bob   Accounting        Bob       2008
1       Jake  Engineering       Jake       2012
2       Lisa  Engineering       Lisa       2004
3        Sue           HR        Sue       2014

In [180]:
results= pd.merge(df1,df2)

In [183]:
pd.DataFrame(results, index=results.employee)  # 노답이넴...

employee Group  hire_date
employee                          
Bob           NaN   NaN        NaN
Jake          NaN   NaN        NaN
Lisa          NaN   NaN        NaN
Sue           NaN   NaN        NaN

In [177]:
pd.DataFrame?

In [163]:
pd.merge(df1,df6, left_index=True, right_on='name')   #?????

Empty DataFrame
Columns: [employee, Group, name, Salary]
Index: []

In [158]:
df1

employee        Group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [159]:
df6

name  Salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [167]:
df8 = pd.DataFrame([['Bob',1],['Jake',2],['Lisa',3],['Sue',4]], columns=['name','Rank'])
df9 = pd.DataFrame([['Bob',3],['Jake',1],['Lisa',4],['Sue',2]], columns=['name','Rank'])

In [168]:
pd.merge(df8,df9,on='name')

name  Rank_x  Rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2